name: Download and release latest snaphot

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:
  
permissions: 
  contents: write

jobs:
  build:
    name: release snapshot
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set env Version
      run:  echo "VERSION=$(curl https://downloads.cardforge.org/dailysnapshots/version.txt)" >> $GITHUB_ENV
    - name: set new tag
      run: |
        echo "${{ env.VERSION }}" > version.txt
        git add version.txt
        git commit -m 'update version.txt'
        git tag test-new
        git push origin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: download archive
      run: |
        wget https://downloads.cardforge.org/dailysnapshots/forge-gui-desktop-$VERSION.tar.bz2
        wget https://downloads.cardforge.org/dailysnapshots/forge-android-$VERSION-signed-aligned.apk
      
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          forge-gui-desktop-${{ env.VERSION }}.tar.bz2
          forge-android-${{ env.VERSION }}-signed-aligned.apk
        tag_name: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
